db:
  restart: always
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: example
    POSTGRES_USER: example
    POSTGRES_DB: example
  volumes:
    - ./postgresql:/var/lib/postgresql
app:
  build: .
  