version: '2'
services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: redis:alpine
    command: ash -c "chown -R redis . && redis-server --appendonly yes"
    ports:
    - 6379:6379
    volumes:
    - ./data/redis:/data
  app:
    build: .
    volumes:
      - ./app:/go/app
    ports:
      - "8000:8000"
    environment:
      APP_PORT: 8000
      DB_HOST: db
      DB_USER: app
      DB_PORT: 5432
      DB_PASSWORD: app
      DB_NAME: app
    depends_on:
      - db
  