version: '2'
services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - ./app:/go/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PORT: 5432
      DB_PASSWORD: app
      DB_NAME: app
    depends_on:
      - db
  